<?php
$xTemplate['top'] = '<div id="thetheTopPanel" class="tspContent"><div class="thethe-content">{%content}</div></div>';
$xTemplate['bottom'] = '<div id="thetheBottomPanel" class="tspContent"><div class="thethe-content">{%content}</div></div>';
$xTemplate['left'] = '<div id="thetheLeftPanel" class="tspContent">{%title}<div class="thethe-content">{%content}</div></div>';
$xTemplate['right'] = '<div id="thetheRightPanel" class="tspContent">{%title}<div class="thethe-content">{%content}</div></div>';
$xTemplate['modal'] = '<div id="thetheModalWindow" class="tspContent">{%title}<div class="tspContentM">{%content}</div></div>';

$xTemplate['js_t'] = 'theme : {%theme}, bgColor : {%bgColor}, borderWidth : {%borderWidth}, borderColor : {%borderColor}, textColor : {%textColor}, tabRadius : {%tabRadius}, radius : {%radius}, shadowSize : {%shadowSize}, shadowColor : {%shadowColor}, opacity : {%opacity}, width : {%width}, widthUnit : {%widthUnit}, height : {%height}, autoOpen : {%autoOpen}, openIn : {%openIn}, autoClose : {%autoClose}, closeAfter : {%closeAfter}, showCloseButton : {%showCloseButton}, closeButtonText : {%closeButtonText}, showTab : {%showTab}, tabText : {%tabText}, speed : {%speed},firstVisitShow : {%firstVisitShow},regularity : {%regularity}, backLink : {%backLink}';
$xTemplate['js_b'] = 'theme : {%theme}, bgColor : {%bgColor}, borderWidth : {%borderWidth}, borderColor : {%borderColor}, textColor : {%textColor}, tabRadius : {%tabRadius}, radius : {%radius}, shadowSize : {%shadowSize}, shadowColor : {%shadowColor}, opacity : {%opacity}, width : {%width}, widthUnit : {%widthUnit}, height : {%height}, autoOpen : {%autoOpen}, openIn : {%openIn}, autoClose : {%autoClose}, closeAfter : {%closeAfter}, showCloseButton : {%showCloseButton}, closeButtonText : {%closeButtonText}, showTab : {%showTab}, tabText : {%tabText}, speed : {%speed},firstVisitShow : {%firstVisitShow},regularity : {%regularity}, backLink : {%backLink}';

$xTemplate['js_l'] = 'theme : {%theme}, bgColor : {%bgColor}, borderWidth : {%borderWidth}, borderColor : {%borderColor}, textColor : {%textColor}, tabRadius : {%tabRadius}, radius : {%radius}, shadowSize : {%shadowSize}, shadowColor : {%shadowColor}, opacity : {%opacity}, width : {%width}, heightUnit : {%heightUnit}, height : {%height}, autoOpen : {%autoOpen}, openIn : {%openIn}, autoClose : {%autoClose}, closeAfter : {%closeAfter}, showCloseButton : {%showCloseButton}, closeButtonText : {%closeButtonText}, showTab : {%showTab}, tabText : {%tabText}, speed : {%speed},firstVisitShow : {%firstVisitShow},regularity : {%regularity}, backLink : {%backLink}';

$xTemplate['js_r'] = 'theme : {%theme}, bgColor : {%bgColor},  borderWidth : {%borderWidth}, borderColor : {%borderColor}, textColor : {%textColor}, tabRadius : {%tabRadius}, radius : {%radius}, shadowSize : {%shadowSize}, shadowColor : {%shadowColor}, opacity : {%opacity}, width : {%width}, heightUnit : {%heightUnit}, height : {%height}, autoOpen : {%autoOpen}, openIn : {%openIn}, autoClose : {%autoClose}, closeAfter : {%closeAfter}, showCloseButton : {%showCloseButton}, closeButtonText : {%closeButtonText}, showTab : {%showTab}, tabText : {%tabText}, speed : {%speed},firstVisitShow : {%firstVisitShow},regularity : {%regularity}, backLink : {%backLink}';

$xTemplate['js_m'] = 'theme : {%theme}, bgColor : {%bgColor}, overlayColor : {%overlayColor}, overlayOpacity : {%overlayOpacity}, borderWidth : {%borderWidth}, borderColor : {%borderColor}, textColor : {%textColor}, radius : {%radius}, shadowSize : {%shadowSize}, shadowColor : {%shadowColor}, opacity : {%opacity}, width : {%width}, height : {%height}, left : {%left}, top : {%top}, right : {%right}, bottom : {%bottom}, closeButtonText : {%closeButtonText}, showCloseButton : {%showCloseButton}, effect : {%effect}, speed : {%speed}, center : {%center}, openIn : {%openIn}, autoClose : {%autoClose}, closeAfter : {%closeAfter}, cookiesName : {%cookiesName},firstVisitShow : {%firstVisitShow},regularity : {%regularity}, backLink : {%backLink}';
	
$GLOBALS['xTemplate'] = $xTemplate;